### ISSUE TITLE
Title of data column

### ISSUE THREAD

**Issue by msh003** [kakusang2020/iXR_GNSS-IMU_TightlyCouplingProgram#2]
Hello
Thank you for sharing your codes. I have a question about the title of each column in the data files. We can download the data, but we do not know their title to adapt our data for use. For example, in Data files in excel format in the "20210302" folder, none of the files has the column title.

**Comment by kakusang2020** [comment]
[Estelleimu03025.csv] is the "Estelle" IMU data on March 2nd，it includes the GPS Time, Acceleration in xyz and gyro in xyz;
[G370imu5th2.csv] is the "Epson G370" IMU fata on March 2nd,  it includes the GPS Time, Acceleration in xyz and gyro in xyz;
[GNSSvel03025.csv] is the velocity by GNSS doppler velocity;
[RTK03025.csv] is the position data by RTK solution;
[Sensor03025.csv] includes temp, press, and so on;
[f9p_5.nav] is convert from f9p to RINEX3.02;
[f9p_5.obs]  is convert from f9p to RINEX3.02;
[poslv03025.csv] is from poslv, as the reference;
[rover_front5.obs]  is convert from f9p to RINEX3.02;
[test2v3.csv] is not for using;
[ubox03025.csv] is the ubox position solution.
